name: integration-tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run app
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:4200

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run e2e
          config-file: cypress.json
          working-directory: cypress
          wait-on: http://localhost:4200
