name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run app
        with:
          start: npm run start
          wait-on: http://localhost:4200

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          wait-on: http://localhost:4200
